---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBK41vQS5r25lcgN9zEwecBUvmH5JKFxP/MFbAVxl41mFKx0GzfjrjF9W8nwZNzBLR40/3GVxUsG2pSK3HAmG2HE+1ANAv12rxPuOPjHqC14VuRg9CI3El/GrqW48YUW05/+S7ap5sU1zWwoqyGaa7O68yV0m3cGOKXVGw2R6cMQLow8OspVbMkQlNS9e89HyRqO5D/IxED2PYWKSQzx0V6aEtpa/9o1cqIVDAszfNeJ3cI5vaLdV9FVVMuSTm9lTWf4LDoukPldorWMhJ0DqnfAC2DuEt5QmKBuzp6Et+2Yd0UWi6E45KMuwxhfhYtnk6srDD4OffICgvJmUrWfcxVjPiQMcDmF6Lr2y69g+BI1pZxEdKL2u4thelcUhkSaKyW7hhh5FpFGK4dZ8F1wOMe3CZleB0zoU2l/5oQMIVBN5+UPFWNhhAm22dTyV4Mf2hRgMWWeO5+Mir1SeS3297YwSgGa2UHTJ/G79vJezfHbK9UayAP6gGPIw0W3ZtK4XCHFpAM0jN3vQIGFN1dwSx4XY95fEPewc4oLyJFmQJSWp+Db6SUkQ9uhtg3ye+PiwpEqsX6c9ksHy3hr02MiAnWsYRhU80Kp/5NKjDOa2mJj0tl2W8QZmC+UkxP3Z5PbLFn46cOFyhnx25wpkOzeQ6FVg1IImmjyOtgVZNe50O6CSV6fYfWwTdfEV44fm3ihO9/WHAWYwSd6oxdYke1Cq3E79EcYerejAS28RE=
    admin-user: AgBumOc7/OKoFyZJoKOJfxvtkY9K9kDv2T5YOEtQVD85WDvY8QEjzI6UenrTaB0xP3i+bPiBFrVVRYQuE9PjR6R6rEEvhDM38s26TR0efDlGBkXfz87sUW0qF6bv0+W19ABUNVDn61HZof8zzT6aJwmkqjEV0tjewW3kobvKkjQpLCE8YcpSgJzPDnxmX6ar8JNNQKHJHRRDcE3Y0Kb2HxLxmdHJaPShuLx3kjHjSRVxcf4z9NU5/0czF21Aohqqex/9S+G2eKtxyaTjiExCzAK5MbCpW46Xo9GioRRYG4j982GNN4WckvlstW726tkxDQK0i40xdhMwRPxK5dxq1CnfrkJWJxwvEtxWOlClj14XOp9UDfFtRayozti4XqPV9w2n9EbXj+B4OpSOB7+PCb3RTta66Hzd6CSrhsxnV4GqKxB2Ky+1REeS59/JaHeT1XCYvW4+Uwh1eZmy6l6tftgaMMvHpA8b3KgCnvdFds9SRI7/Q80X0e7zaPR5acvmBWxDpESLwzz4rYYQg5pQGg/MgogRq19OrJ3ATdJwbpP/MnWfTg+FCHIMvZJfQYFueJih7h0QXPyi+a1oN7gYjaFVXD3EzexFXP5BqJhw+nwF91Z9Ht9arLA864xPA++ZwAWGQO16sp6DbjoBfDetkkv40Lez3QDcU/Wzn+99KLzFEl30dyAUyOe4ZCzkgBH+rVN+vFykKQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
