---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgCCXxKfyI39H3j3w+ym9U19iBVRDjzeYr8lImzZNOuFyJqMDullycEfjNQuiDSh5Qdj+lQqNarlSVN7yJ7s5GKRp3aDoD0DwRsaV69WomY2E4M66FB4YfdA8S2ZPBaU0u9qNUsdBU1iTOv9SZNwaFKx96CQXGN3Eu+uZZ7aAVZCd0HqkinoP8l9rUqI2GzzBuQPQMcIQ1tAvIKjjk01fD72YZJvQVXR+cnXsVi/0Zg5LrGqHeJg+6wZd4Kto9Ay/Lc2fcUC5TIZR76AXHalbq2NG1ybg7FhstK+JFwpZQMMHzbuJfL/UKB2nLRX/skkgHblRqevPRvPNWPpe2TCkHgjx5B8TPqQWRhbh5xcR8LOnCcSftRoZa3pF4tNQLdbkAezS+PRDOceTuPCTFgEV060cXfa9mPHzDO32did99VOhVoVLWxC+kFeZz8c4fnWOmVpU0Otx0c6ahiMFq6rBxXDORuO/h8QAlCLg9zmoIESU8WX67Rmw+UxcOQHDsmwR6/N0PdkpAeVEiKZyhJCVN825hSPNvzAqYLtZKAS2WpVRIqcjULXjCTrFqQ3OnB0o581kj+IM/gCKtLLHZfb4RGtccguJDJ1zvVShTV3ynzew+tvXay1uafyNAeBEowfX9N4bTIZbSUrYCfcpCCF0xV7uvYJ3a6C+3NCsBTDdXD59d07Hw6oh5SZMKZjMb1bQNf8ldhmKySY1p7oQdcnckSxhUA6XyyrEUj3Fk0=
    username: AgCl2KesdNpluQmm5Bw0QiQiL0su4RopTm+rdP34PNYE5dx1JIrBKCmobzz9vSDrjm60mrQTYpybHgoiMw29f/dJ1a8tySs4b5ENLNcRrAYHZ0Lg0UKiHTd1xMD0esWUcwPnbnFKHII7APFgclIukEk0LqoPFjaUfcR0hGMnFm4ybIlDMfy/2Fb/DedlPwPUyYiUhmShV0x8jT8AeYJP3dfBlPH74OOpMOibNhfukvSsDUblFVKxExXBXwyfNMoVklAbERd9FIuzomqBZZZjPrt/pDLs4pFNH+IA78dbqCBAS77W688uyBpF8DRsN13cuxhbsh/iegZHKAdIlmet9y1hqUQyy4WNegVDxF9kTfLPOuxwemFhZKmy+lXnw+/TrHFHLWMdXfskbmT68sbcsoVbkhI97eDZJhZE9bzWTCxxAJ1SfyeulB4TJD7qnZ2IqRy8ehUpY12yxBE7IwtSXaxc67S79Gs1fNsPzgbzIARR9+4/B4drjjYIljAXYT2RLIajk9Iiq+6WJ5vtOj+jRvck1/+EouyrWEbO5L/BqQ8RllN+kTbjvZBKT2ibgli4mGrbbupYq3ILQMxKxnL5HlhzglCCIhNXl0kAg6VngEmwaToR54R0m+PplrLIIeyK+0ZGM969wH43RJOW4kID5RkoB134+p2DGBAianxda5Y9wUpmKcIokyT+jOzZeLUiR1iO0Fmc0q4EIA==
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
