apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/abdinbayov/qoves-platform.git
    targetRevision: HEAD
    path: manifests/django-api
  destination:
    server: https://kubernetes.default.svc
    namespace: django-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
